const CATEGORY_ALL_POSTS = "All Posts";
const CATEGORY_BASICS = "Basics";
const CATEGORY_WEB_DEVELOPMENT = "Web";
const KEY_ENTER = "13";
const PATH_ALL_POSTS = "/posts";
const PATH_CATEGORY_BASICS = "/category/basics";
const PATH_CATEGORY_WEB_DEVELOPMENT = "/category/web";

module.exports = {
  CATEGORY_ALL_POSTS,
  CATEGORY_BASICS,
  CATEGORY_WEB_DEVELOPMENT,
  KEY_ENTER,
  PATH_ALL_POSTS,
  PATH_CATEGORY_BASICS,
  PATH_CATEGORY_WEB_DEVELOPMENT,
};
