const NUM_OF_CATEGORIES = 10;
const NUM_OF_MENUS = 2;

const MENU_WEB_DEVELOPMENT = "Web Development";
const MENU_BASICS = "Basics";

const CATEGORY_JAVASCRIPT = "JavaScript";
const CATEGORY_REACT = "React";
const CATEGORY_REDUX = "Redux";
const CATEGORY_NODEJS = "NodeJS";
const CATEGORY_ANGULAR_TYPESCRIPT = "Angular | TypeScript"; 
const CATEGORY_CSS = "CSS";

const CATEGORY_CODING_PROBLEMS = "Coding Problems";
const CATEGORY_PROGRAMMING_BASICS = "Programming Basics";
const CATEGORY_JAVA = "Java";
const CATEGORY_SDLC = "SDLC";

const MENU_HIERARCHY = {
  [MENU_WEB_DEVELOPMENT]: [
    CATEGORY_JAVASCRIPT,
    CATEGORY_REACT,
    CATEGORY_REDUX,
    CATEGORY_NODEJS, // nodejs
    CATEGORY_ANGULAR_TYPESCRIPT, // angular|typescript
    CATEGORY_CSS,
  ],
  [MENU_BASICS]: [
    CATEGORY_CODING_PROBLEMS, // coding-problems
    CATEGORY_PROGRAMMING_BASICS, // programming-basics
    CATEGORY_JAVA,
    CATEGORY_SDLC,
  ],
};

const REVERSE_MENU_HIERARCHY = {
  [CATEGORY_JAVASCRIPT]: MENU_WEB_DEVELOPMENT,
  [CATEGORY_REACT]: MENU_WEB_DEVELOPMENT,
  [CATEGORY_REDUX]: MENU_WEB_DEVELOPMENT,
  [CATEGORY_NODEJS]: MENU_WEB_DEVELOPMENT,
  [CATEGORY_ANGULAR_TYPESCRIPT]: MENU_WEB_DEVELOPMENT,
  [CATEGORY_CSS]: MENU_WEB_DEVELOPMENT,
  [CATEGORY_CODING_PROBLEMS]: MENU_BASICS,
  [CATEGORY_PROGRAMMING_BASICS]: MENU_BASICS,
  [CATEGORY_JAVA]: MENU_BASICS,
  [CATEGORY_SDLC]: MENU_BASICS,
};

module.exports = {
  NUM_OF_CATEGORIES,
  NUM_OF_MENUS,
  MENU_WEB_DEVELOPMENT,
  MENU_BASICS,
  CATEGORY_JAVASCRIPT,
  CATEGORY_REACT,
  CATEGORY_REDUX,
  CATEGORY_NODEJS,
  CATEGORY_ANGULAR_TYPESCRIPT,
  CATEGORY_CSS,
  CATEGORY_CODING_PROBLEMS,
  CATEGORY_PROGRAMMING_BASICS,
  CATEGORY_JAVA,
  CATEGORY_SDLC,
  MENU_HIERARCHY,
  REVERSE_MENU_HIERARCHY,
};
